# permissions for end users to edit externalsecretaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: externalsecretaccess-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secretsbeam-operator
    app.kubernetes.io/part-of: secretsbeam-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalsecretaccess-editor-role
rules:
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretaccesses/status
  verbs:
  - get
