# permissions for end users to view secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kscp-operator
    app.kubernetes.io/part-of: kscp-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalsecret-viewer-role
rules:
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecrets/status
  verbs:
  - get
