# permissions for end users to view externalsecretproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: externalsecretprovider-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kscp-operator
    app.kubernetes.io/part-of: kscp-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalsecretprovider-viewer-role
rules:
- apiGroups:
  - kscp.io
  resources:
  - externalsecretproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kscp.io
  resources:
  - externalsecretproviders/status
  verbs:
  - get
