---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kscp.io
  resources:
  - externalsecretaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kscp.io
  resources:
  - externalsecretaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - kscp.io
  resources:
  - externalsecretaccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kscp.io
  resources:
  - externalsecretproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kscp.io
  resources:
  - externalsecretproviders/finalizers
  verbs:
  - update
- apiGroups:
  - kscp.io
  resources:
  - externalsecretproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kscp.io
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kscp.io
  resources:
  - externalsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - kscp.io
  resources:
  - externalsecrets/status
  verbs:
  - get
  - patch
  - update
