## Append samples of your project ##
resources:
- secrets_v1alpha1_externalsecret.yaml
- secrets_v1alpha1_externalsecretaccess.yaml
- secrets_v1alpha1_externalsecretprovider.yaml
#+kubebuilder:scaffold:manifestskustomizesamples