apiVersion: kscp.io/v1alpha1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/instance: secret-sample
    app.kubernetes.io/part-of: kscp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kscp-operator
  name: secret-sample
spec:
  provider: aws
  secretName: stuff
  secretString: stuff
  providerSpec: {}
  # TODO(user): Add fields here