apiVersion: orbitops.dev/v1alpha1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/instance: secret-sample
    app.kubernetes.io/part-of: secretsbeam-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secretsbeam-operator
  name: secret-sample
spec:
  provider: aws
  externalName: /test/stuff/stuff
  random:
    regex: '.'
    size: 12