apiVersion: orbitops.dev/v1alpha1
kind: ExternalSecretProvider
metadata:
  labels:
    app.kubernetes.io/name: secretprovider
    app.kubernetes.io/instance: secretprovider-sample
    app.kubernetes.io/part-of: secretsbeam-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secretsbeam-operator
  name: aws
spec:
  provider: aws
  config:
    oidcProviderArn: "arn:aws:iam::$ACCOUNT:oidc-provider/$PROVIDER_ID"
  # TODO(user): Add fields here